/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RubricsRouteImport } from './routes/rubrics'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssessRouteImport } from './routes/assess'
import { Route as IndexRouteImport } from './routes/index'

const RubricsRoute = RubricsRouteImport.update({
  id: '/rubrics',
  path: '/rubrics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessRoute = AssessRouteImport.update({
  id: '/assess',
  path: '/assess',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assess': typeof AssessRoute
  '/auth': typeof AuthRoute
  '/rubrics': typeof RubricsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assess': typeof AssessRoute
  '/auth': typeof AuthRoute
  '/rubrics': typeof RubricsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assess': typeof AssessRoute
  '/auth': typeof AuthRoute
  '/rubrics': typeof RubricsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/assess' | '/auth' | '/rubrics'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assess' | '/auth' | '/rubrics'
  id: '__root__' | '/' | '/assess' | '/auth' | '/rubrics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessRoute: typeof AssessRoute
  AuthRoute: typeof AuthRoute
  RubricsRoute: typeof RubricsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rubrics': {
      id: '/rubrics'
      path: '/rubrics'
      fullPath: '/rubrics'
      preLoaderRoute: typeof RubricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assess': {
      id: '/assess'
      path: '/assess'
      fullPath: '/assess'
      preLoaderRoute: typeof AssessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessRoute: AssessRoute,
  AuthRoute: AuthRoute,
  RubricsRoute: RubricsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
