/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RubricsRouteImport } from './routes/rubrics'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssessRouteImport } from './routes/assess'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeedbackIdRouteImport } from './routes/feedback.$id'

const RubricsRoute = RubricsRouteImport.update({
  id: '/rubrics',
  path: '/rubrics',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessRoute = AssessRouteImport.update({
  id: '/assess',
  path: '/assess',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackIdRoute = FeedbackIdRouteImport.update({
  id: '/feedback/$id',
  path: '/feedback/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assess': typeof AssessRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/performance': typeof PerformanceRoute
  '/rubrics': typeof RubricsRoute
  '/feedback/$id': typeof FeedbackIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assess': typeof AssessRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/performance': typeof PerformanceRoute
  '/rubrics': typeof RubricsRoute
  '/feedback/$id': typeof FeedbackIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assess': typeof AssessRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/performance': typeof PerformanceRoute
  '/rubrics': typeof RubricsRoute
  '/feedback/$id': typeof FeedbackIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assess'
    | '/auth'
    | '/history'
    | '/performance'
    | '/rubrics'
    | '/feedback/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assess'
    | '/auth'
    | '/history'
    | '/performance'
    | '/rubrics'
    | '/feedback/$id'
  id:
    | '__root__'
    | '/'
    | '/assess'
    | '/auth'
    | '/history'
    | '/performance'
    | '/rubrics'
    | '/feedback/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessRoute: typeof AssessRoute
  AuthRoute: typeof AuthRoute
  HistoryRoute: typeof HistoryRoute
  PerformanceRoute: typeof PerformanceRoute
  RubricsRoute: typeof RubricsRoute
  FeedbackIdRoute: typeof FeedbackIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rubrics': {
      id: '/rubrics'
      path: '/rubrics'
      fullPath: '/rubrics'
      preLoaderRoute: typeof RubricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assess': {
      id: '/assess'
      path: '/assess'
      fullPath: '/assess'
      preLoaderRoute: typeof AssessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/$id': {
      id: '/feedback/$id'
      path: '/feedback/$id'
      fullPath: '/feedback/$id'
      preLoaderRoute: typeof FeedbackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessRoute: AssessRoute,
  AuthRoute: AuthRoute,
  HistoryRoute: HistoryRoute,
  PerformanceRoute: PerformanceRoute,
  RubricsRoute: RubricsRoute,
  FeedbackIdRoute: FeedbackIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
